# JVM memory for Gradle daemon
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

# Enable Gradle build cache (faster builds)
org.gradle.caching=false

# Parallel builds (safe for most Spring projects)
org.gradle.parallel=true

# Kotlin code style
kotlin.code.style=official

# Optional: improves Gradle performance
org.gradle.configuration-cache=false

org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk-21.jdk/Contents/Home
distributionUrl=https\://services.gradle.org/distributions/gradle-8.10-bin.zip