package com.finance.service.impl

import org.springframework.ai.chat.prompt.Prompt
import org.springframework.ai.ollama.OllamaChatModel
import com.finance.service.AIParserService
import org.slf4j.LoggerFactory
import org.springframework.ai.converter.ListOutputConverter
import org.springframework.core.convert.support.DefaultConversionService
import org.springframework.stereotype.Service


@Service
class AIParserServiceImpl(
    private val chatModel: OllamaChatModel ) : AIParserService{

    companion object {
        // Replaces Lombok's @Slf4j log instance
        private val log = LoggerFactory.getLogger(AIParserServiceImpl::class.java)
    }

    override fun parse(text: String): List<String> {

        val prompt = """
            Extract transactions from this bank statement.

            Return JSON array:
            [
              {
                "date": "...",
                "amount": ...,
                "merchant": "...",
                "type": "...",
                "currency": "SGD"
              }
            ]

            TEXT:
            $text
        """.trimIndent()

        val response = generateListLocally(prompt)

        return response
    }

    /**
     * Internal function for other backend classes to call.
     * It uses the streaming API underneath but blocks until completion to return a clean String.
     */

    fun analyzeDataLocally(userPrompt: String): String {
        val aiPrompt = Prompt(userPrompt)

        // Consume the streaming data packets internally and compile them into a String
        val finalResult = chatModel.stream(aiPrompt)
            .map { response -> response.result?.output?.content ?: "" }
            .filter { token -> token.isNotEmpty() }
            .collectList()                    // Collects stream fragments to Mono<List<String>>
            .map { list -> list.joinToString("") } // Joins fragments into a single string text block
            .block()                          // Synchronously block until completion

        return finalResult ?: "No response generated by the local AI engine."
    }

    // Implement the new List method
    fun generateListLocally(userPrompt: String): List<String> {
        // 1. Create a converter that transforms plain text comma-separated or JSON lists into a Kotlin List
        val converter = ListOutputConverter(DefaultConversionService())

        // 2. Format your prompt to append strict formatting rules that the AI must follow
        val formatInstructions = converter.format
        val completePromptText = "$userPrompt\n\n$formatInstructions"
        val aiPrompt = Prompt(completePromptText)

        // 3. Collect the stream tokens into a single text block
        val rawTextResult = chatModel.stream(aiPrompt)
            .map { response -> response.result?.output?.content ?: "" }
            .filter { token -> token.isNotEmpty() }
            .collectList()
            .map { list -> list.joinToString("") }
            .block() ?: ""

        // 4. Let the converter transform the text string safely into a List<String>
        return converter.convert(rawTextResult) ?: emptyList()
    }

}